# ID стикеров

DONUTS = [
    'CAACAgIAAxkBAAEEa0FiUYfj-OYcvvT0h0j0RALYQO1BYQACWgYAAlOx9wPjI8yrDumkkyME',
    'CAACAgIAAxkBAAEEaz9iUYe2Dh2AepJcxEN_rRTN3mCNngACpgMAAvoLtggCp5fVMWSEvyME',
    'CAACAgIAAxkBAAEEaz1iUYeFyiAqy5qoCynObGoRAgYuIAACtQIAAkcVaAk4LbxZ_Ei6mSME',
]
